'use client'
import {useEffect,useState} from 'react'
import {ArrowUpRight,ChevronDown,Menu,X,Plus} from 'lucide-react'
const thesis=[['01','AI','Artificial Intelligence','AI platforms, agents, applied intelligence and intelligent software.'],['02','SOFTWARE','Software & Platforms','Vertical software, developer tools, SaaS and digital platforms.'],['03','DATA','Data & Intelligence','Data infrastructure, analytics, knowledge systems and decision intelligence.'],['04','CYBER','Cybersecurity','Identity, cloud security, AI security and critical digital infrastructure.'],['05','SPACE','Space & Connectivity','Satellite communications, Earth observation and next-generation connectivity.'],['06','DEEPTECH','DeepTech & Infrastructure','Compute, data centres, robotics, energy and advanced technology.']]
const map=[['01','INTELLIGENCE','AI · Agents · Data · Software'],['02','INFRASTRUCTURE','Compute · Data Centres · Cybersecurity'],['03','CONNECTIVITY','Satellite · Telecom · Networks'],['04','PHYSICAL SYSTEMS','Robotics · Energy · DeepTech']]
export default function Page(){const[open,setOpen]=useState(false);const[active,setActive]=useState('');useEffect(()=>{const els=document.querySelectorAll('.reveal');const o=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('in')),{threshold:.12});els.forEach(e=>o.observe(e));const links=['about','thesis','lab','portfolio','intelligence','press','contact'];const on=()=>{let x='';for(const id of links){const el=document.getElementById(id);if(el&&scrollY>=el.offsetTop-180)x=id}setActive(x)};addEventListener('scroll',on);return()=>{o.disconnect();removeEventListener('scroll',on)}},[]);const nav=(id:string)=><a className={active===id?'active':''} href={'#'+id} onClick={()=>setOpen(false)}>{id==='thesis'?'Investment':id[0].toUpperCase()+id.slice(1)}</a>;return <><header><div className="nav"><a className="brand" href="#top">PAJIC<span>.</span><small>HOLDING · TECHNOLOGY · VENTURES</small></a><nav className={open?'open':''}>{['about','thesis','lab','portfolio','intelligence','press'].map(id=>nav(id))}</nav><a className="navcta" href="#contact">CONTACT <ArrowUpRight size={14}/></a><button className="menub" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></header><main id="top">
<section className="hero"><div className="heroGlow"/><div className="wrap heroIn reveal"><div className="eyebrow">TECHNOLOGY INVESTMENT · VENTURE BUILDING · EMERGING MARKETS</div><h1>We invest in<br/><em>what comes next.</em></h1><p>PAJIC is a technology investment and venture-building platform focused on AI, software, data, cybersecurity, space, connectivity and DeepTech.</p><div className="actions"><a className="gold" href="#thesis">OUR INVESTMENT THESIS <ArrowUpRight/></a><a className="ghost" href="#contact">WORK WITH PAJIC</a></div></div><div className="heroMeta">01 — 07 <span>TECHNOLOGY · CAPITAL · EXECUTION</span></div></section>
<section id="about" className="wrap section reveal"><div className="split"><div><div className="eyebrow">01 / ABOUT PAJIC</div><h2>Technology is changing the map.</h2></div><p>We back technologies with the potential to reshape industries, create new markets and build durable advantage. Our perspective combines deep technology understanding with an emerging-market lens.</p></div><div className="imageHero"><img src="https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=2200&q=82"/><div className="imageLabel">DIGITAL INFRASTRUCTURE <span>↗</span></div></div></section>
<section id="thesis" className="dark section"><div className="wrap reveal"><div className="split"><div><div className="eyebrow">02 / INVESTMENT THESIS</div><h2>Structural advantage.</h2></div><p>Our focus spans the technology stack — from intelligent software and data to the infrastructure that powers the digital economy.</p></div><div className="cards">{thesis.map(([n,k,t,d])=><article key={n} className="card"><span>{n} / {k}</span><h3>{t}</h3><p>{d}</p><Plus className="plus" size={18}/></article>)}</div></div></section>
<section className="feature"><div className="featureImg"><img src="https://images.unsplash.com/photo-1517976547714-720226b864c1?auto=format&fit=crop&w=1800&q=82"/></div><div className="featureCopy reveal"><div className="eyebrow">03 / CONNECTIVITY</div><h2>From infrastructure beneath us to networks above us.</h2><p className="quote">The next technology cycle will be built across physical and digital infrastructure.</p><p>Satellite · Telecom · Infrastructure</p></div></section>
<section id="lab" className="lab section"><div className="wrap reveal"><div className="labGrid"><div><div className="eyebrow">04 / PAJIC AI LAB</div><h2>From opportunity<br/>to company.</h2></div><div><p>PAJIC AI Lab identifies high-potential AI opportunities and helps turn them into companies through pre-seed investment, technology strategy and venture building.</p><div className="tags"><span>AI</span><span>AGENTS</span><span>DATA</span><span>PAKISTAN</span></div></div></div></div></section>
<section className="dark section"><div className="wrap reveal"><div className="split"><div><div className="eyebrow">05 / PAJIC TECHNOLOGY MAP</div><h2>The layers shaping the future.</h2></div><p>A focused view across the systems where PAJIC sees structural opportunity.</p></div><div className="map">{map.map(([n,t,d])=><div className="mapCard" key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></div>)}</div></div></section>
<section id="portfolio" className="section"><div className="wrap reveal"><div className="split"><div><div className="eyebrow">06 / PORTFOLIO</div><h2>Building the next generation.</h2></div><p>A focused portfolio across AI, software, data, space and DeepTech.</p></div><div className="portfolio"><article><span>AI PLATFORM · PAKISTAN</span><h3>PakAI</h3><p>Democratizing intelligence for Pakistan.</p><ArrowUpRight/></article><article><span>VENTURE BUILDING</span><h3>PAJIC<br/>AI Lab</h3><p>Pre-seed AI ventures and company creation.</p><ArrowUpRight/></article><article><span>FUTURE INVESTMENTS</span><h3>Next.</h3><p>AI · Software · Data · Space · DeepTech</p><ArrowUpRight/></article></div></div></section>
<section id="intelligence" className="dark section"><div className="wrap reveal"><div className="eyebrow">07 / PAJIC INTELLIGENCE</div><div className="intel"><h2>Ideas, markets<br/><em>& technology.</em></h2><p>Perspectives on technology, emerging markets, infrastructure and the companies shaping what comes next.</p><a className="ghost" href="#press">VIEW INSIGHTS <ArrowUpRight/></a></div></div></section>
<section id="press" className="press section"><div className="wrap reveal"><div className="eyebrow">PRESS</div><h2>PAJIC in the news.</h2><article className="pressCard"><div><span>PAJIC AI LAB · 2026</span><h3>PAJIC AI Lab Pre-Seeds Two AI Startups to Democratize AI Access in Pakistan</h3></div><ArrowUpRight/></article></div></section>
<section id="contact" className="contact section"><div className="wrap reveal"><div className="eyebrow">CONTACT PAJIC</div><div className="contactGrid"><div><h2>Let's work<br/><em>together.</em></h2><p>Technology founders, investors, strategic partners and emerging-market opportunities.</p></div><div className="details"><div><small>ADDRESS</small><p>PAJIC Tower, Ph7, Bahria Town,<br/>Islamabad 44000, Pakistan</p></div><div><small>EMAIL</small><p><a href="mailto:contact@pajic.ltd">contact@pajic.ltd</a></p></div><div><small>PHONE</small><p><a href="tel:+923378000008">+92 337 8000008</a></p></div></div></div></div></section></main><footer><div className="wrap foot"><span>© 2026 PAJIC Holding Ltd. All rights reserved.</span><span>ISLAMABAD · PAKISTAN · EMERGING MARKETS / GLOBAL</span></div></footer></>}
